CREATE DATABASE UNIVERSIDAD;
USE UNIVERSIDAD;

CREATE TABLE CARRERA (
    CARRERA_ID INT AUTO_INCREMENT PRIMARY KEY,
    CARRERA VARCHAR(4000) NOT NULL
);

CREATE TABLE DOCENTE (
    DOCENTE_ID INT NOT NULL PRIMARY KEY,
    NOMBRES VARCHAR(4000) NOT NULL,
    APELLIDOS VARCHAR(4000) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CORREO VARCHAR(4000) NOT NULL,
    TELEFONO INT NOT NULL,
    DIRECCION VARCHAR(4000) NOT NULL,
    DPI INT NOT NULL,
    FECHA_INSCRIPCION DATE NOT NULL DEFAULT CURRENT_DATE()
);

CREATE TABLE ESTUDIANTE (
    ESTUDIANTE_ID INT NOT NULL PRIMARY KEY,
    CARRERA_ID INT NOT NULL,
    NOMBRES VARCHAR(4000) NOT NULL,
    APELLIDOS VARCHAR(4000) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CORREO VARCHAR(4000) NOT NULL,
    TELEFONO INT NOT NULL,
    DIRECCION VARCHAR(4000) NOT NULL,
    DPI INT NOT NULL,
    FECHA_INSCRIPCION DATE NOT NULL DEFAULT CURRENT_DATE(),
    CREDITOS INT NOT NULL DEFAULT 0,
    FOREIGN KEY (CARRERA_ID) REFERENCES CARRERA(CARRERA_ID)
);

CREATE TABLE CURSO (
    CURSO_ID INT NOT NULL PRIMARY KEY,
    CARRERA_ID INT NOT NULL,
    CURSO VARCHAR(4000) NOT NULL,
    CREDITOS_NECESARIOS INT NOT NULL,
    CREDITOS_OTORGA INT NOT NULL,
    OBLIGATORIO INT NOT NULL,
    FOREIGN KEY (CARRERA_ID) REFERENCES CARRERA(CARRERA_ID)
);

CREATE TABLE CURSOHABILITADO (
    CURSO_HABILITADO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CICLO VARCHAR(4000) NOT NULL,
    CURSO_ID INT NOT NULL,
    DOCENTE_ID INT NOT NULL,
    SECCION CHAR(2) NOT NULL,
    CUPO INT NOT NULL,
    ANIO INT NOT NULL DEFAULT YEAR(CURDATE()),
    NUMERO_ASIGNADOS INT NOT NULL DEFAULT 0,
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(CURSO_ID),
    FOREIGN KEY (DOCENTE_ID) REFERENCES DOCENTE(DOCENTE_ID)
);
    
CREATE TABLE HORARIO (
    CURSO_HABILITADO_ID INT NOT NULL,
    FECHA INT NOT NULL,
    HORARIO VARCHAR(4000) NOT NULL,
    FOREIGN KEY (CURSO_HABILITADO_ID) REFERENCES CURSOHABILITADO(CURSO_HABILITADO_ID)
);

CREATE TABLE ACTA (
    ACTA_ID INT AUTO_INCREMENT PRIMARY KEY,
    ACTA_FECHA DATE NOT NULL
);

CREATE TABLE ASIGNACION (
    CURSO_HABILITADO_ID INT NOT NULL,
    ESTADO INT NOT NULL DEFAULT 1,
    ESTUDIANTE_ID INT NOT NULL,
    ACTA_ID INT,
    NOTA INT,
    FOREIGN KEY (ACTA_ID) REFERENCES ACTA(ACTA_ID),
    FOREIGN KEY (CURSO_HABILITADO_ID) REFERENCES CURSOHABILITADO(CURSO_HABILITADO_ID),
    FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTE(ESTUDIANTE_ID)
);

CREATE TABLE HISTORIAL (
    FECHA DATE NOT NULL DEFAULT CURRENT_DATE(),
    DESCRIPCION VARCHAR(4000) NOT NULL,
    TIPO VARCHAR(4000) NOT NULL
);
